hashrocket/dotmatrix

.ctags
This lets ctags create tags for nested CoffeeScript constants like:
Seq25.Note
=> Create tags for nested CoffeeScript constants

.ackrc
Using the syntax before ack was looking inside the log folder and taking a whole lot of time.
=> Separates ignored dirs into different flags.

.sharedrc
=> Reset empty files after `gnap`

bin/vimbundles.sh
Setting the `--depth=1` option on clone makes cloning faster and take less disk space since it uses a shallow clone. 
This means only a shallow copy of the codebase at the latest commit is actually being pulled rather than the whole git history tree with every revision ever made.
The same applies for updating plugins, we now call `git pull` with `--depth=1`.
=> Clone a shallow copy of vim plugins

.sharedrc
Deleted files were being added to git stage by `git add -N` so the user was not being prompted.
=> Prompt for deleted files on `gnap`

.vim/after/syntax/ruby.vim
Ruby 2.3 added the squiggly heredoc literal
http://ruby-doc.org/core-2.3.0/doc/syntax/literals_rdoc.html#label-Here+Documents
=> Add support for PSQL squiggly heredoc highlighting in Ruby

.irbrc
If you close your `rails console` or `irb` the history will be persisted.
So next time you open it just use the arrows UP/DOWN to get your history back.
=> Save history for IRB and Rails console

.clippy.rb, .irbrc, .pryrc
IRB is not required by default:
```sh
micah@local:~% ruby -e IRB
-e:1:in `<main>': uninitialized constant IRB (NameError)
```
I have some scripts that start a Pry console via `Pry.start`. Because the `.pryrc` requires the `.irbrc` and that uses the `IRB` constant I get errors.
The only shared behavior that I can see is the clippy code. I extracted this code into another dotfile and required it from each `.pryrc` and `.irbrc`. This fixes the problem. Not sure if this is the best place for the clippy code to live, or if it should be extracted into a gem and required conditionally?
=> Remove IRB dependency from Pry

bin/upgrade
After you upgrade, list the new commits so that a user can more easily see what has changed.
=> Add basic log output when upgrading

README.md, bin/dot_functions.sh, bin/install
All I've done here is wrap the loop that copies the `.gitconfig.local` file in a conditional that looks for a `--workstation` flag.
My reasoning is that Dotmatrix is a open-source project we encourage people to use and yet the default installation tries to make the machine a Hashrocket Workstation. I don't think that's very friendly and we've been working on reducing the Hashrocket-specific things - this seems like a prime candidate.
This change does mean that when you *are* setting up a Hashrocket Workstation you have to remember to pass that flag, but I think that's worth it. Even if you forget, it's really just as simple as:
```
$ cp .gitconfig.local ~/
```
One more thing: that loop is probably overkill for the one `.local` file that we've got. It's nice that if we had another `.local` …
=> Require flag for workstation install

.gitconfig
This is a handy alias we've ported across several machines in the Hashrocket office. Now we all can use it.
=> Add `cheddar` as an alias

.vimrc
This makes it easy to pull up man pages within Vim using, for example,
`:Man grep`.
=> Enable the built-in man page plugin

hr/libexec/hr-battery
This is general-purpose battery percentage indicator for laptops. There
are quite a few formatters included, and several options.
It is known to work with Ubuntu and Mac OS, and even works on Ubuntu
running through Vagrant/VirtualBox (my use case).
The --tmux option is useful for tmux status bar output. For example, in
my current tmux config, I have the following:
set -g status-right ' #(hr battery --format="[%%percent]" --charging --color --tmux)'
=> Add hr battery command

.zshrc, hr/libexec/hr-init, hr/libexec/hr-sh-cd
When opening `psql` with the PGDATABASE env var set
the connected database will be the name in the env
var.
This feature relies on the convention of having a database
with the same name as the project but with `_development` as
a suffix.
When hcd is used, the PGDATABASE env var is set and
we acquire the convienience of only ever needing to type
`psql`.
=> Set the PGDATABASE env var when hcd is used

.vimrc
Included the autocommand for running NeoFormat on save but it is
commented out to allow OPT-IN - in case you are working with a client
that has not bought into NeoFormat for some reason.
=> Add NeoFormat Settings

.sharedrc
This is an alias I use often to reword, edit, squash, fixup, and execute on Git commits prior to merging a feature branch or opening a pull request. `master` is a Git reference to where your branch diverges from our standard default branch, `master`. I think adding this to Dotmatrix will encourage users to pare down their Git history to just the essential information.
=> Add an alias for rebasing feature branches

.prettierrc, .vimbundle, .vimrc
Since ALE is capable of autoformatting code and linting there is no need
for NeoFormat.
ALE's autoformatting also allows using lambda functions and allows to
easily disable autoformatting for a buffer which comes in handy when
running `:Btabedit`.
This also removes the forced prettier configuration that was hardcoded into
vimrc. Instead place a .prettierrc in your $HOME folder which you can
override with a .prettierrc file in your project dir.
=> Remove NeoFormat in favor of ALE for formatting

.psqlrc
I've had this setting turned on for years on every machine I use. It's unobtrusive and can provide interesting and useful information.
=> Turn on psql timing

.psqlrc
Co-authored-by: Jake Worth <jake.worth@hashrocket.com>
Co-authored-by: Philip Capel <phil.capel@hashrocket.com>
With this setting, psql will create a unique history file for each database it connects to, in the format of `.psql_history-your-database-name`.
This extends the number of commands that can be saved for each database by isolating them, and reduces the chance of running a destructive command in a remote psql session.
More info:
https://til.hashrocket.com/posts/c2cb0fd702-know-your-histfile
=> Allow psql to use a different history for each DB

.tmux.conf
Run this in tmux to see if you have true color support
```
awk 'BEGIN{
s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
for (colnum = 0; colnum<77; colnum++) {
r = 255-(colnum*255/76);
g = (colnum*510/76);
b = (colnum*255/76);
if (g>255) g = 510-g;
printf "\033[48;2;%d;%d;%dm", r,g,b;
printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
printf "%s\033[0m", substr(s,colnum+1,1);
}
printf "\n";
}'
```
=> True colors for tmux

.sharedrc
On a fresh Fedora 32 system with zsh installed and a fresh install of
dotmatrix the following error is experienced when typing a command at
the prompt:
```
/$HOME/.sharedrc:61: defining function based on alias `ls`
/$HOME/.sharedrc:61: parse error near `()`
zsh: git_prompt_info: command not found...
```
Since `git_prompt_info` is defined in .sharedrc and since it is not able
to be parsed we end up with a few errors, all of which are resolved by
changing the syntax for declaring this function.
=> Updated .sharedrc l func declaration

.vimbundle
Josh Davey changed his branch naming from master to main, this enables Plug to locate the correct branch.
=> Use main branch for tslime and turbux
